size:
  horizontal: 1500   # (in pixels)
  vertical: 1200     # (in pixels)

geometry:
  # Berry properties
  overlap: 0.2         # berry overlap (as percentage of radius)
  radius: 0.4          # berry radius (in pixels)
  thickness: 5         # berry border thickness

  # Bar properties
  length_ratio: 0.4
  width_ratio: 0.7
  overhang_ratio: 0.5
  font: 'simplex'

# Berry Scaling
scaling:
  0: 1
  1: 0.9
  2: 1
  3: 1.1

filename: 'example_12_test.png' 